apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-upf
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oai-upf
  template:
    metadata:
      labels:
        app: oai-upf
    spec:
      containers:
      - name: oai-upf
        image: oaisoftwarealliance/oai-upf:latest
        ports:
        - containerPort: 80
