apiVersion: apps/v1
kind: Deployment
metadata:
  name: smf-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smf
  template:
    metadata:
      labels:
        app: smf
    spec:
      containers:
      - name: smf
        image: oaisoftwarealliance/oai-smf:latest
        ports:
          - containerPort: 38413  # Port SCTP pour le SMF
        volumeMounts:
          - name: smf-config-volume
            mountPath: /openair-smf/config/smf-config.yaml  # Chemin dans le conteneur
            subPath: smf-config.yaml  # Nom du fichier monté
      volumes:
        - name: smf-config-volume
          configMap:
            name: smf-config  # Le nom du ConfigMap créé précédemment
