//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AMFSpec) DeepCopyInto(out *AMFSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AMFSpec.
func (in *AMFSpec) DeepCopy() *AMFSpec {
	if in == nil {
		return nil
	}
	out := new(AMFSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NRFSpec) DeepCopyInto(out *NRFSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NRFSpec.
func (in *NRFSpec) DeepCopy() *NRFSpec {
	if in == nil {
		return nil
	}
	out := new(NRFSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAICluster) DeepCopyInto(out *OAICluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAICluster.
func (in *OAICluster) DeepCopy() *OAICluster {
	if in == nil {
		return nil
	}
	out := new(OAICluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OAICluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAIClusterList) DeepCopyInto(out *OAIClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OAICluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAIClusterList.
func (in *OAIClusterList) DeepCopy() *OAIClusterList {
	if in == nil {
		return nil
	}
	out := new(OAIClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OAIClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAIClusterSpec) DeepCopyInto(out *OAIClusterSpec) {
	*out = *in
	out.AMF = in.AMF
	out.SMF = in.SMF
	out.UPF = in.UPF
	out.NRF = in.NRF
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAIClusterSpec.
func (in *OAIClusterSpec) DeepCopy() *OAIClusterSpec {
	if in == nil {
		return nil
	}
	out := new(OAIClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAIClusterStatus) DeepCopyInto(out *OAIClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAIClusterStatus.
func (in *OAIClusterStatus) DeepCopy() *OAIClusterStatus {
	if in == nil {
		return nil
	}
	out := new(OAIClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SMFSpec) DeepCopyInto(out *SMFSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SMFSpec.
func (in *SMFSpec) DeepCopy() *SMFSpec {
	if in == nil {
		return nil
	}
	out := new(SMFSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPFSpec) DeepCopyInto(out *UPFSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPFSpec.
func (in *UPFSpec) DeepCopy() *UPFSpec {
	if in == nil {
		return nil
	}
	out := new(UPFSpec)
	in.DeepCopyInto(out)
	return out
}
