apiVersion: apps/v1
kind: Deployment
metadata:
  name: smf-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smf
  template:
    metadata:
      labels:
        app: smf
    spec:
      containers:
      - name: smf
        image: openairinterface/smf:latest
        ports:
          - containerPort: 38413  
        volumeMounts:
          - name: smf-config-volume
            mountPath: /openair-smf/config/smf-config.yaml  
            subPath: smf-config.yaml  
      volumes:
        - name: smf-config-volume
          configMap:
            name: smf-config  
