---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oai.openai.com
  resources:
  - oaicores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oai.openai.com
  resources:
  - oaicores/finalizers
  verbs:
  - update
- apiGroups:
  - oai.openai.com
  resources:
  - oaicores/status
  verbs:
  - get
  - patch
  - update
