apiVersion: v1
kind: ConfigMap
metadata:
  name: amf-config
  namespace: default
data:
  amf-config.yaml: |
    nrf:
      ip: 10.0.0.1
    amf:
      interface: eth0
      plmn:
        mcc: "001"
        mnc: "01"
      guami:
        - plmn_id:
            mcc: "001"
            mnc: "01"
          amf_id: "0001"
      security:
        integrity_order: [NIA2, NIA1, NIA0]
        ciphering_order: [NEA0, NEA1, NEA2]
