apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: oaiclusters.oai.com  # Utilisez le pluriel pour la ressource
spec:
  group: oai.com
  names:
    kind: OAICluster
    plural: oaiclusters  # Pluriel
    singular: oaicluster
    shortNames:
      - oai
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                amf:
                  type: object
                  properties:
                    replicaCount:
                      type: integer
                      default: 1
                smf:
                  type: object
                  properties:
                    replicaCount:
                      type: integer
                      default: 1
                upf:
                  type: object
                  properties:
                    replicaCount:
                      type: integer
                      default: 1
                nrf:
                  type: object
                  properties:
                    replicaCount:
                      type: integer
                      default: 1
