apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: oaiclusters.oai.com
spec:
  group: oai.com
  names:
    kind: OAICluster
    plural: oaiclusters
    singular: oaicluster
    shortNames:
      - oai
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                amf:
                  type: object
                  properties:
                    replicaCount:
                      type: integer
                      default: 1
                    image:  # Ajoutez ce champ
                      type: string
                      default: "oaisoftwarealliance/oai-amf:latest"
                smf:
                  type: object
                  properties:
                    replicaCount:
                      type: integer
                      default: 1
                    image:  # Ajoutez ce champ
                      type: string
                      default: "oaisoftwarealliance/oai-smf:latest"
                upf:
                  type: object
                  properties:
                    replicaCount:
                      type: integer
                      default: 1
                    image:  # Ajoutez ce champ
                      type: string
                      default: "oaisoftwarealliance/oai-upf:latest"
                nrf:
                  type: object
                  properties:
                    replicaCount:
                      type: integer
                      default: 1
                    image:  # Ajoutez ce champ
                      type: string
                      default: "oaisoftwarealliance/oai-nrf:latest"
